### PR TITLE
fixed race around global resource

### PR DESCRIPTION
**Pull request by franklinwise**
stringShuffle uses rand.Intn, which is global, and when multple threads call ConnectWithDialer a race between threads will occur on the rand library.

### CODE REVIEW

**Comment by samuel** [comment]
Thanks for the patch but it shouldn't be necessary according to http://golang.org/pkg/math/rand/ :

    The default Source is safe for concurrent use by multiple goroutines.

Was there an issue that you were having that this fixed?

**Comment by franklinwise** [comment]
The go race detector detects this as a race condition.
 
screen shot 2015-04-02 at 9 36 49 pm

**Comment by samuel** [comment]
If I have the same version of the file as you then line number `util.log:38` is `s[i], s[j] = s[j], s[i]` which means the race is on the server list. I made a change to copy the server list rather than mutate and keep a reference.

Let me know if this fixes the race for you.

https://github.com/samuel/go-zookeeper/commit/a7d37a38aabc11845c777f640e535e920bd662af

**Comment by rbastic** [comment]
I think the go race detector is lying here. You should report this as a bug to the Go team, perhaps. If you aren't going to report it, please mention it as such so that maybe someone else will.

**Comment by samuel** [comment]
Closing this as I believe it's not an issue in this package. Feel free to reopen if you feel otherwise.

**Pull request closed without merging**
