### PR TITLE
modify buffer len

### PR DESCRIPTION
**Pull request by cuiweixie**
buffer len no need to add 16.

### CODE REVIEW

**Comment by alxzh** [comment]
This will runtime panic "slice bounds out of range" http://play.golang.org/p/BNsfPqKfp7

**Comment by cuiweixie** [comment]
open the link http://play.golang.org/p/BNsfPqKfp7, and show' "Forbidden".
I think something went wrong.

**Comment by alxzh** [comment]
Code is very easy, it is the same as in the file you are patching. In case if result size in bigger than capacity of the slice bugger reinitialized with response size (look at line 582). In this case your code will panic.

Example (try to put this into play.golang.org and run):
package main

func main() {
	blen := 10
	buf := make([]int, blen)

	_ = buf[:16+blen]
}

**Comment by samuel** [comment]
Thanks for the patch. I merged a different PR that fixed the same issue.

**Pull request closed without merging**
