### PR TITLE
MOD: support chroot for a connection

### PR DESCRIPTION
**Pull request by git-hulk**
Support chroot for the connection, or the user has to support this feature by wrapping the interface.

### CODE REVIEW

**Comment by git-hulk** [comment]
hi, @samuel 

anyone can review this pr? and we really need this feature.

**Comment by git-hulk** [comment]
@gpaul @theatrus @dougm anyone can review this PR?

**Comment by git-hulk** [comment]
@samuel can you review this pr?

**Comment by git-hulk** [comment]
ok, I’m going to close this in a week if nobody replies

**Comment by chennqqi** [comment]
Anyone else? this feature may be very useful in enterprise

**Pull request closed without merging**
