### PR TITLE
expose connection session id

### PR DESCRIPTION
**Pull request by dallasmarlow**

### CODE REVIEW

**Comment by ayrb13** [comment]
It is same as what i did.
HAHA

**Comment by samuel** [comment]
Thanks for the patch, unfortunately this introduces a data race. Need to atomically set/get the session ID for it to be safe. There's only a few places it's used though so should be pretty straightforward.

**Comment by dallasmarlow** [comment]
@samuel thanks for pointing that out, just updated with atomic stores

**Comment by talbright** [comment]
This is something I could use in my current project.

In some cases it's important to know your session ID, so that you can determine if you are the owner of a znode (``ephemeralOwner``). For example, the zookeeper ensemble goes down, and then comes back up before your session times out.

**Comment by dallasmarlow** [comment]
@talbright I'm not sure, but I think the session timeout issue is an encoding problem. it is something i've seen as well (https://github.com/samuel/go-zookeeper/issues/82)

**Comment by talbright** [comment]
It may even be worse than that, but I'm still waiting for some time to investigate it further. I left my go-zookeeper client running, shut down my zk server, and brought it up minutes later. My session still didn't expire. Not sure yet though if that's a client issue, a server setting problem, or some conceptual thing I'm missing.

**Comment by nomis52** [comment]
Can this be merged please.

**Comment by sakateka** [comment]
@samuel

**Comment by samuel** [comment]
Looks good. Thanks!

**Pull request merged**
