### PR TITLE
Hostprovider

### PR DESCRIPTION
**Pull request by zellyn**
Add variadic options to zk.Connect, and a `HostProvider` interface based on the Java code. An initial `DNSHostprovider` is the default, matching Java's implementation.

### CODE REVIEW

**Comment by zellyn** [comment]
This has been running for two or three weeks now here at Square.

cc: @bwester

**Comment by talbright** [comment]
@zellyn how well has this library been working for you at square?

**Comment by samuel** [comment]
Awesome, this is great work and definitely needed. Thanks for submitting it. The connect options are a good call.

**Comment by zellyn** [comment]
@talbright Fine so far, although tbh I haven't tracked how many consumers have redeployed their apps since I made the change…

Still, it's a pretty straightforward change, with pretty good tests: I don't think there's much to worry about. :smile:

**Comment by zellyn** [comment]
@samuel fwiw, I don't think ConnectWithDialer is really used: I couldn't find any non-tests usages in SourceGraph.

**Comment by talbright** [comment]
I was more curious of your overall experience with go-zookeeper, as we are considering using it for one of our projects (we already have Zookeeper with Clojure clients). If you happen to know of an example of leadership detection in go-zeekeeper that would be awesome.

Apologies for hijacking the PR discussion :skull:

**Comment by zellyn** [comment]
@talbright I'm zellyn@{twitter,gmail.com,squareup.com,etc.} if you want to chat offline. More info on our zookeeper experience from Josh Humphries, my manager: https://groups.google.com/d/msg/mechanical-sympathy/GmyKrZn2Zus/AgBGJZ-eBwAJ

**Comment by talbright** [comment]
Thanks for the info and offer, will reach out to you offline. :beers:

**Comment by dragonsinth** [comment]
@zellyn Did you ever extend / implement a version of DNSHostProvider that (re-)resolves hostnames periodically / lazily / on error?

**Comment by zellyn** [comment]
@dragonsinth nope - we have no custom code beyond what's in this repo. Our zookeeper hosts change extremely rarely, if ever.

**Comment by dragonsinth** [comment]
Thanks for the info.  Not a huge issue for us either, but we run on Google Compute Engine and recently I had to avoid doing full machine destroy/creates on our ZK nodes after finding out the hard way in staging that none of our clients will try to re-resolve hostnames when the IPs change. :)

**Comment by zellyn** [comment]
I'm guessing the change wouldn't be too difficult, though… :-)

**Pull request merged**
